### ISSUE TITLE
missing assembly signature

### ISSUE THREAD

**Issue by Nazario-DApote** [Real-Serious-Games/Fluent-State-Machine#5]
the assembly in nuget has no 'Strong Name'

**Comment by RoryDungan** [comment]
I can sign it with a strong name, but do you know the best practice for commiting the PFX file to GitHub? If it's used to identify the package author I figure I probably shouldn't commit it, but if it doesn't exist the project fails to build.

**Comment by Nazario-DApote** [comment]
Where is the problem?

in Windows
sn -k Fluent-State-Machine.snk

add your key to the project file .csproj

  <PropertyGroup>
    <AssemblyOriginatorKeyFile>Fluent-State-Machine.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

Without a strong name every assemblies referring your Fuent-State-Machine from NuGet cannot be strong signed.

**Comment by RoryDungan** [comment]
Okay I've created a SNK file, signed the assembly and pushed a new version to Nuget. Ran `sn -v Fluent-State-Machine.dll` and it said the assembly was valid but let me know if you have any issues. It may take a few mins for the package to get indexed by Nuget.

**Comment by Nazario-DApote** [comment]
Thanks very much!
